apiVersion: v1
kind: Pod
metadata:
  name: pod-secure-2
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /app/config
          name: config-volume
      securityContext:
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
  volumes:
    - name: config-volume
      emptyDir:
        sizeLimit: 500Mi
